### PR TITLE
image.php: calculate maximum image height instead of guessing it

### PR DESCRIPTION
**Pull request by citronalco**

### CODE REVIEW

**Comment by citronalco** [comment]
Added [WIP] to title: I noticed that videos have the wrong size, too, and also want to fix that.

**Comment by acrylian** [comment]
I am not really familar with this theme to that detail. But actually CSS should handle especially videos responsively and for images we have some maxspace function to already calculate images fitting to specific height/width. Nevertheless thanks, I will just pull that in.

**Comment by acrylian** [comment]
Once you got most issue we'll create a new release version for the theme and announce it via our site. Perhaps even as 1.2 since its a bit with the other PR that I will just take in finally, too.

**Comment by citronalco** [comment]
Thanks. I'll let you know.

**Pull request merged**
